-- https://pastebin.com/8Pjy0qGY от 12.05.2025
Truncate Table nrpz.erc_${year}_list_contract;
Insert into nrpz.erc_${year}_list_contract
WITH con as (SELECT con.rnk,
				con.positionnumber,
				con.rnk_number,
				con.ikz,
				con.signdate,
				con.publishdate_first ,
				con.publishdate_last ,
				con.versionnumber_first ,
				con.versionnumber_last ,
				con.notificationnumber ,
				con.lotnumber ,
				con.sop_name ,
				con.singlecustomer_name,
				con.protocoldate ,
				con.price ,
				con.price_cur ,
				con.stage ,
				con.executions_date,
				con.rejected_date,
				con.rejected_paid,
				con.rejected_reason,
				con.rejected_reason_name,
				con.penalties_type,
				con.penalties_party,
				con.penalties_amount,
				con.executionperiod_end ,
				--con.supplier_type,
				con.supplier_fullname,
				con.supplier_inn,
				con.supplier_kpp,
				con.object_name ,
				con.org_name ,
				con.org_inn ,
				con.org_spz ,
				con.org_kgntv_contract,
				con.protocoldate_publ,
				con.protocoldate_sign,
				con.protocoldate_one_publ,
				con.protocoldate_one_sign,
				con.firstnoticesuccesdate,
				con.flag_16,
				con.cnt_modif,
				con.type_,
				con.flag_evasion,
				con.pricetype,
                con.lotid, --правки от 30.06.23 добавить lot id
                con.is_structured_form,
                con.requestid,
				con.contract_project_number, 
				con.contract_price_changed_supplier_protocol, 
				con.justification_contract_price_change
From nrpz.erc_${year}_contract con	
Where date_trunc('day',con.signdate) < to_date('${date}','yyyy-mm-dd') --конец отч периода
),
contracts AS (
    SELECT DISTINCT
        con.rnk,
        con.ikz,
        con.notificationnumber,
        con.lotnumber
    FROM nrpz.erc_${year}_contract con
    WHERE date_trunc('day', con.signdate) < to_date('${date}', 'yyyy-mm-dd')
)
-- 1 блок
Select
	Distinct sch.org_name,
	sch.org_inn,
	sch.org_spz,
	sch.org_kgntv,
	sch.grbsid,
	sch.plannumber,
	sch.versionnumber,
	sch.publishdate,
	sch.positionnumber,
	sch.ikz,
	sch.nmc_schedule,
	sch.purchasecanceled,
	sch.specialpurchase_type,
	sch.cnt_modif_pg,
	sch.reqnum,
	sch.publishdate_reqnum,
	sch.sop_code_reqnum,
	sch.sop_name_reqnum,
	sch.joflag_org_name,
	sch.joflag_org_spz,
	sch.org_kgntv_joflag,
	sch.joflag,
	sch.startdate,
	sch.enddate,
	sch.nmc_reqnum,
	sch.nmc_joflag,
	sch.biddingdate,
	sch.openingdate,
	sch.scoringdate,
	sch.prequalification,
	sch.lotnumber,
	sch.positionnumber_reqnum,
	sch.flag_comp_reqnum,
	sch.ikz_reqnum,
	sch.plannumber_reqnum,
	sch.object_name_reqnum,
	sch.cnt_modif_reqnum,
	sch.flag_cans_reqnum,
	sch.purchasenumber_rn,
	sch.flah_act_version,
	sch.flag_smp, -- флаг смп от 01.04.2025
	con.rnk,
	con.rnk_number,
	con.ikz ikz_con,
	con.signdate,
	con.publishdate_first publishdate_con,
	con.publishdate_last publishdate_con_last,
	con.versionnumber_first versionnumber_con,
	con.versionnumber_last versionnumber_con_last,
	con.notificationnumber reqnum_con,
	con.lotnumber lotnumber_con,
	con.sop_name sop_name_con,
	con.singlecustomer_name oneex_con,
	con.protocoldate protocoldate_con,
	con.price ck_first,
	con.price_cur ck_last,
	con.stage stage_con,
	con.executions_date,
	con.rejected_date,
	con.rejected_paid,
	con.rejected_reason,
	con.rejected_reason_name,
	con.penalties_type,
	con.penalties_party,
	con.penalties_amount,
	con.executionperiod_end plan_execution_date_con,
	--con.supplier_type,
	con.supplier_fullname,
	con.supplier_inn,
	con.supplier_kpp,
	con.object_name object_name_con,
	con.org_name org_name_con,
	con.org_inn org_inn_con,
	con.org_spz org_spz_con,
	con.org_kgntv_contract,
	con.protocoldate_publ,
	con.protocoldate_sign,
	con.protocoldate_one_publ,
	con.protocoldate_one_sign,
	con.firstnoticesuccesdate,
	con.flag_16,
	con.cnt_modif cnt_modif_con,
	con.type_,
	con.flag_evasion,
	con.pricetype,
    con.lotid, --правки от 30.06.23 добавить lot id
    con.is_structured_form,
    con.requestid,
	con.contract_project_number, 
	con.contract_price_changed_supplier_protocol, 
	con.justification_contract_price_change
From nrpz.erc_${year}_list sch
Inner Join con on  (sch.joflag = 0 And con.notificationnumber = sch.reqnum And con.lotnumber = sch.lotnumber) --несовместные
-- 20.07.2022 добавлено ограничение, чтобы попадали закупки по тем ГРБС, которые учитываются в рейтинге			
inner join nrpz.erc_dwh_organization_kgntv dok on sch.org_kgntv = dok.id
inner join nrpz.erc_dwh_organization_kgntv dokgrbs   on dokgrbs.id = dok.parentid and dokgrbs.id <> 3039
inner join nrpz.ERC_ORGANIZATION eo   on eo.spz = dokgrbs.spz
			
Union 
 -- 2 блок
Select 
	Distinct sch.org_name,
	sch.org_inn,
	sch.org_spz,
	sch.org_kgntv,
	sch.grbsid,
	sch.plannumber,
	sch.versionnumber,
	sch.publishdate,
	sch.positionnumber,
	sch.ikz,
	sch.nmc_schedule,
	sch.purchasecanceled,
	sch.specialpurchase_type,
	sch.cnt_modif_pg,
	sch.reqnum,
	sch.publishdate_reqnum,
	sch.sop_code_reqnum,
	sch.sop_name_reqnum,
	sch.joflag_org_name,
	sch.joflag_org_spz,
	sch.org_kgntv_joflag,
	sch.joflag,
	sch.startdate,
	sch.enddate,
	sch.nmc_reqnum,
	sch.nmc_joflag,
	sch.biddingdate,
	sch.openingdate,
	sch.scoringdate,
	sch.prequalification,
	sch.lotnumber,
	sch.positionnumber_reqnum,
	sch.flag_comp_reqnum,
	sch.ikz_reqnum,
	sch.plannumber_reqnum,
	sch.object_name_reqnum,
	sch.cnt_modif_reqnum,
	sch.flag_cans_reqnum,
	sch.purchasenumber_rn,
	sch.flah_act_version,
	sch.flag_smp, -- флаг смп от 01.04.2025
	con.rnk,
	con.rnk_number,
	con.ikz ikz_con,
	con.signdate,
	con.publishdate_first publishdate_con,
	con.publishdate_last publishdate_con_last,
	con.versionnumber_first versionnumber_con,
	con.versionnumber_last versionnumber_con_last,
	con.notificationnumber reqnum_con,
	con.lotnumber lotnumber_con,
	con.sop_name sop_name_con,
	con.singlecustomer_name oneex_con,
	con.protocoldate protocoldate_con,
	con.price ck_first,
	con.price_cur ck_last,
	con.stage stage_con,
	con.executions_date,
	con.rejected_date,
	con.rejected_paid,
	con.rejected_reason,
	con.rejected_reason_name,
	con.penalties_type,
	con.penalties_party,
	con.penalties_amount,
	con.executionperiod_end plan_execution_date_con,
	--con.supplier_type,
	con.supplier_fullname,
	con.supplier_inn,
	con.supplier_kpp,
	con.object_name object_name_con,
	con.org_name org_name_con,
	con.org_inn org_inn_con,
	con.org_spz org_spz_con,
	con.org_kgntv_contract,
	con.protocoldate_publ,
	con.protocoldate_sign,
	con.protocoldate_one_publ,
	con.protocoldate_one_sign,
	con.firstnoticesuccesdate,
	con.flag_16,
	con.cnt_modif cnt_modif_con,
	con.type_,
	con.flag_evasion,
	con.pricetype,
    con.lotid, --правки от 30.06.23 добавить lot id
    con.is_structured_form,
    con.requestid,
	con.contract_project_number, 
	con.contract_price_changed_supplier_protocol, 
	con.justification_contract_price_change
From nrpz.erc_${year}_list sch
Inner Join con on (con.positionnumber = sch.positionnumber  And sch.reqnum Is Null) -- ед.поставщик
-- 20.07.2022 добавлено ограничение, чтобы попадали закупки по тем ГРБС, которые учитываются в рейтинге			
inner join nrpz.erc_dwh_organization_kgntv dok on sch.org_kgntv = dok.id
inner join nrpz.erc_dwh_organization_kgntv dokgrbs   on dokgrbs.id = dok.parentid and dokgrbs.id <> 3039
inner join nrpz.ERC_ORGANIZATION eo  on eo.spz = dokgrbs.spz

Union 
 -- 3 блок 
Select 
	Distinct sch.org_name,
	sch.org_inn,
	sch.org_spz,
	sch.org_kgntv,
	sch.grbsid,
	sch.plannumber,
	sch.versionnumber,
	sch.publishdate,
	sch.positionnumber,
	sch.ikz,
    sch.nmc_schedule,
	sch.purchasecanceled,
	sch.specialpurchase_type,
	sch.cnt_modif_pg,
	sch.reqnum,
	sch.publishdate_reqnum,
	sch.sop_code_reqnum,
	sch.sop_name_reqnum,
	sch.joflag_org_name,
	sch.joflag_org_spz,
	sch.org_kgntv_joflag,
	sch.joflag,
	sch.startdate,
	sch.enddate,
	sch.nmc_reqnum,
	sch.nmc_joflag,
	sch.biddingdate,
	sch.openingdate,
	sch.scoringdate,
	sch.prequalification,
	sch.lotnumber,
	sch.positionnumber_reqnum,
	sch.flag_comp_reqnum,
	sch.ikz_reqnum,
	sch.plannumber_reqnum,
	sch.object_name_reqnum,
	sch.cnt_modif_reqnum,
	sch.flag_cans_reqnum,
	sch.purchasenumber_rn,
	sch.flah_act_version,
	sch.flag_smp, -- флаг смп от 01.04.2025
	con.rnk,
	con.rnk_number,
	con.ikz ikz_con,
	con.signdate,
	con.publishdate_first publishdate_con,
	con.publishdate_last publishdate_con_last,
	con.versionnumber_first versionnumber_con,
	con.versionnumber_last versionnumber_con_last,
	con.notificationnumber reqnum_con,
	con.lotnumber lotnumber_con,
	con.sop_name sop_name_con,
	con.singlecustomer_name oneex_con,
	con.protocoldate protocoldate_con,
	con.price ck_first,
	con.price_cur ck_last,
	con.stage stage_con,
	con.executions_date,
	con.rejected_date,
	con.rejected_paid,
	con.rejected_reason,
	con.rejected_reason_name,
	con.penalties_type,
	con.penalties_party,
	con.penalties_amount,
	con.executionperiod_end plan_execution_date_con,
	--con.supplier_type,
	con.supplier_fullname,
	con.supplier_inn,
	con.supplier_kpp,
	con.object_name object_name_con,
	con.org_name org_name_con,
	con.org_inn org_inn_con,
	con.org_spz org_spz_con,
	con.org_kgntv_contract,
	con.protocoldate_publ,
	con.protocoldate_sign,
	con.protocoldate_one_publ,
	con.protocoldate_one_sign,
	con.firstnoticesuccesdate,
	con.flag_16,
	con.cnt_modif cnt_modif_con,
	con.type_,
	con.flag_evasion,
	con.pricetype,
    con.lotid, --правки от 30.06.23 добавить lot id
    con.is_structured_form,
    con.requestid,
	con.contract_project_number, 
	con.contract_price_changed_supplier_protocol, 
	con.justification_contract_price_change
From nrpz.erc_${year}_list sch
Inner Join con on (sch.joflag = 1 And con.notificationnumber = sch.reqnum And con.lotnumber = sch.lotnumber And con.org_kgntv_contract = sch.org_kgntv) --совместная, у которых есть контракт
-- 20.07.2022 добавлено ограничение, чтобы попадали закупки по тем ГРБС, которые учитываются в рейтинге			
inner join nrpz.erc_dwh_organization_kgntv dok on sch.org_kgntv = dok.id
inner join nrpz.erc_dwh_organization_kgntv dokgrbs   on dokgrbs.id = dok.parentid and dokgrbs.id <> 3039
inner JOIN nrpz. ERC_ORGANIZATION eo   on eo.spz = dokgrbs.spz

Union
-- 4 блок
Select 
	Distinct sch.org_name,
	sch.org_inn,
	sch.org_spz,
	sch.org_kgntv,
	sch.grbsid,
	sch.plannumber,
	sch.versionnumber,
	sch.publishdate,
	sch.positionnumber,
	sch.ikz,
	sch.nmc_schedule,
	sch.purchasecanceled,
	sch.specialpurchase_type,
	sch.cnt_modif_pg,
	sch.reqnum,
	sch.publishdate_reqnum,
	sch.sop_code_reqnum,
	sch.sop_name_reqnum,
	sch.joflag_org_name,
	sch.joflag_org_spz,
	sch.org_kgntv_joflag,
	sch.joflag,
	sch.startdate,
	sch.enddate,
	sch.nmc_reqnum,
	sch.nmc_joflag,
	sch.biddingdate,
	sch.openingdate,
	sch.scoringdate,
	sch.prequalification,
	sch.lotnumber,
	sch.positionnumber_reqnum,
	sch.flag_comp_reqnum,
	sch.ikz_reqnum,
	sch.plannumber_reqnum,
	sch.object_name_reqnum,
	sch.cnt_modif_reqnum,
	sch.flag_cans_reqnum,
	sch.purchasenumber_rn,
	sch.flah_act_version,
	sch.flag_smp, -- флаг смп от 01.04.2025
	con.rnk,
	con.rnk_number,
	con.ikz ikz_con,
	con.signdate,
	con.publishdate_first publishdate_con,
	con.publishdate_last publishdate_con_last,
	con.versionnumber_first versionnumber_con,
	con.versionnumber_last versionnumber_con_last,
	con.notificationnumber reqnum_con,
	con.lotnumber lotnumber_con,
	con.sop_name sop_name_con,
	con.singlecustomer_name oneex_con,
	con.protocoldate protocoldate_con,
	con.price ck_first,
	con.price_cur ck_last,
	con.stage stage_con,
	con.executions_date,
	con.rejected_date,
	con.rejected_paid,
	con.rejected_reason,
	con.rejected_reason_name,
	con.penalties_type,
	con.penalties_party,
	con.penalties_amount,
	con.executionperiod_end plan_execution_date_con,
	--con.supplier_type,
	con.supplier_fullname,
	con.supplier_inn,
	con.supplier_kpp,
	con.object_name object_name_con,
	con.org_name org_name_con,
	con.org_inn org_inn_con,
	con.org_spz org_spz_con,
	con.org_kgntv_contract,
	con.protocoldate_publ,
	con.protocoldate_sign,
	con.protocoldate_one_publ,
	con.protocoldate_one_sign,
	con.firstnoticesuccesdate,
	con.flag_16,
	con.cnt_modif cnt_modif_con,
	con.type_,
	con.flag_evasion,
    con.pricetype,
    con.lotid, --правки от 30.06.23 добавить lot id
    con.is_structured_form,
    con.requestid,
	con.contract_project_number, 
	con.contract_price_changed_supplier_protocol, 
	con.justification_contract_price_change
From nrpz.erc_${year}_list sch
Left Join con on (sch.joflag = 1 And con.notificationnumber = sch.reqnum And con.lotnumber = sch.lotnumber And con.org_kgntv_contract = sch.org_kgntv) --совместная joflag=1, у которых **нет ещё** контракта
-- 20.07.2022 добавлено ограничение, чтобы попадали закупки по тем ГРБС, которые учитываются в рейтинге			
inner join nrpz.erc_dwh_organization_kgntv dok on sch.org_kgntv = dok.id
inner join nrpz.erc_dwh_organization_kgntv dokgrbs   on dokgrbs.id = dok.parentid and dokgrbs.id <> 3039
inner join nrpz.ERC_ORGANIZATION eo   on eo.spz = dokgrbs.spz
Where con.rnk Is Null And sch.joflag = 1

union 
-- 5 блок 
Select 
	Distinct sch.org_name,
	sch.org_inn,
	sch.org_spz,
	sch.org_kgntv,
	sch.grbsid,
	sch.plannumber,
	sch.versionnumber,
	sch.publishdate,
	sch.positionnumber,
	sch.ikz,
	sch.nmc_schedule,
	sch.purchasecanceled,
	sch.specialpurchase_type,
	sch.cnt_modif_pg,
	sch.reqnum,
	sch.publishdate_reqnum,
	sch.sop_code_reqnum,
	sch.sop_name_reqnum,
	sch.joflag_org_name,
	sch.joflag_org_spz,
	sch.org_kgntv_joflag,
	sch.joflag,
	sch.startdate,
	sch.enddate,
	sch.nmc_reqnum,
	sch.nmc_joflag,
	sch.biddingdate,
	sch.openingdate,
	sch.scoringdate,
	sch.prequalification,
	sch.lotnumber,
	sch.positionnumber_reqnum,
	sch.flag_comp_reqnum,
	sch.ikz_reqnum,
	sch.plannumber_reqnum,
	sch.object_name_reqnum,
	sch.cnt_modif_reqnum,
	sch.flag_cans_reqnum,
	sch.purchasenumber_rn,
	sch.flah_act_version,
	sch.flag_smp, -- флаг смп от 01.04.2025
	NULL rnk,
	NULL rnk_number,
	NULL ikz_con,
	NULL::timestamp signdate,
	Null::timestamp publishdate_con,
	Null::timestamp publishdate_con_last,
	NULL::int2 versionnumber_con,
	NULL::int2 versionnumber_con_last,
	NULL reqnum_con,
	NULL::int8 lotnumber_con,
	NULL sop_name_con,
	NULL oneex_con,
	NULL::timestamp protocoldate_con,
	NULL::numeric(24,4) ck_first,
	NULL::numeric(24,4) ck_last,
	NULL stage_con,
	NULL::timestamp executions_date,
	Null::timestamp rejected_date,
	Null::NUMERIC(24,4) rejected_paid,
	NULL rejected_reason,
	NULL rejected_reason_name,
	NULL penalties_type,
	NULL penalties_party,
	Null::NUMERIC(24,4) penalties_amount,
	NULL::timestamp plan_execution_date_con,
	--NULL supplier_type,
	NULL supplier_fullname,
	NULL supplier_inn,
	NULL supplier_kpp,
	NULL object_name_con,
	NULL org_name_con,
	NULL org_inn_con,
	NULL org_spz_con,
	Null::NUMERIC(24,4) org_kgntv_contract,
	Null::timestamp protocoldate_publ,
	Null::timestamp protocoldate_sign,
	Null::timestamp protocoldate_one_publ,
	Null::timestamp protocoldate_one_sign,
	Null::timestamp firstnoticesuccesdate,
	NULL::int4 flag_16,
	NULL::int8 cnt_modif_con,
	NULL type_,
	Null::int4 flag_evasion,
	NULL pricetype,
    NULL::int4 lotid,
    NULL is_structured_form,
	NULL::int4 requestid,
	NULL contract_project_number, 
	NULL::boolean contract_price_changed_supplier_protocol, 
	NULL justification_contract_price_change
From nrpz.erc_${year}_list sch
-- 20.07.2022 добавлено ограничение, чтобы попадали закупки по тем ГРБС, которые учитываются в рейтинге			
inner join nrpz.erc_dwh_organization_kgntv dok on sch.org_kgntv = dok.id
inner join nrpz.erc_dwh_organization_kgntv dokgrbs on dokgrbs.id = dok.parentid and dokgrbs.id <> 3039
inner join nrpz.ERC_ORGANIZATION eo   on eo.spz = dokgrbs.spz
LEFT JOIN nrpz.erc_dwh_procedures_kgntv_${srez_number} p ON sch.reqnum = p.reqnum
Left Join contracts con_1 On (sch.joflag = 1 And con_1.notificationnumber = sch.reqnum And con_1.lotnumber = sch.lotnumber) --извещения совм. 3 блок
Left Join contracts con_2 On (sch.joflag = 0 And con_2.notificationnumber = sch.reqnum And con_2.lotnumber = sch.lotnumber) --извещения несовм. 1 блок
Left Join contracts con_3 on (con_3.ikz = sch.ikz And sch.reqnum Is Null) --контракты из плана-графика, то есть ед.поставщик 2 блок
Where con_1.rnk Is Null And con_2.rnk Is Null And con_3.rnk Is NULL;


Insert Into nrpz.erc_${year}_list_contract
Select 
	Distinct 
	sch.org_name,
	sch.org_inn,
	sch.org_spz,
	sch.org_kgntv,
	sch.grbsid,
	sch.plannumber,
	sch.versionnumber,
	sch.publishdate,
	sch.positionnumber,
	sch.ikz,
	sch.finance_total nmc_schedule,
	sch.purchasecanceled,
	sch.specialpurchase_type,
	sch.modiff_all cnt_modif_pg,
	Null reqnum,
	NULL::timestamp publishdate_reqnum,
	Null sop_code_reqnum,
	Null sop_name_reqnum,
	Null joflag_org_name,
	Null joflag_org_spz,
	NULL::int2 org_kgntv_joflag,
	NULL::int2 joflag,
	Null::timestamp startdate,
	Null::timestamp enddate,
	NULL::numeric nmc_reqnum,
	NULL::numeric nmc_joflag,
	Null::timestamp biddingdate,
	Null::timestamp openingdate,
	Null::timestamp scoringdate,
	Null prequalification,
	NULL::int4 lotnumber,
	Null positionnumber_reqnum,
	Case 
		When con.singlecustomer_name like 'Пункт 25 части 1 статьи 93%' OR con.singlecustomer_name IS null
		Then 1 Else 0 End flag_comp_reqnum, -- правка от 01.10.24
	Null ikz_reqnum,
	Null plannumber_reqnum,
	Null object_name_reqnum,
	NULL::int4 cnt_modif_reqnum,
	NULL::int2 flag_cans_reqnum,
	NULL::int2 purchasenumber_rn,
	sch.flah_act_version,
	0 flag_smp, -- флаг смп от 01.04.2025
	con.rnk,
	con.rnk_number,
	con.ikz ikz_con,
	con.signdate,
	con.publishdate_first publishdate_con,
	con.publishdate_last publishdate_con_last,
	con.versionnumber_first versionnumber_con,
	con.versionnumber_last versionnumber_con_last,
	con.notificationnumber reqnum_con,
	con.lotnumber lotnumber_con,
	con.sop_name sop_name_con,
	con.singlecustomer_name oneex_con,
	con.protocoldate protocoldate_con,
	con.price ck_first,
	con.price_cur ck_last,
	con.stage stage_con,
	con.executions_date,
	con.rejected_date,
	con.rejected_paid,
	con.rejected_reason,
	con.rejected_reason_name,
	con.penalties_type,
	con.penalties_party,
	con.penalties_amount,
	con.executionperiod_end plan_execution_date_con,
	--con.supplier_type,
	con.supplier_fullname,
	con.supplier_inn,
	con.supplier_kpp,
	con.object_name object_name_con,
	con.org_name org_name_con,
	con.org_inn org_inn_con,
	con.org_spz org_spz_con,
	con.org_kgntv_contract,
	con.protocoldate_publ,
	con.protocoldate_sign,
	con.protocoldate_one_publ,
	con.protocoldate_one_sign,
	con.firstnoticesuccesdate,
	con.flag_16,
	con.cnt_modif cnt_modif_con,
	con.type_,
	con.flag_evasion,
	con.pricetype,
    con.lotid, --правки от 30.06.23 добавить lot id
    con.is_structured_form,
    con.requestid,
	con.contract_project_number, 
	con.contract_price_changed_supplier_protocol, 
	con.justification_contract_price_change
From nrpz.erc_${year}_schedule_pos sch
Inner Join nrpz.erc_${year}_contract con On (con.ikz = sch.ikz) --закупки (икз) у которых есть контракты, которых нет в list + не берем аукц. в электрон форме
Where con.rnk not in (Select Distinct rnk 
					  From nrpz.erc_${year}_list_contract
					  Where rnk Is Not Null)
And con.sop_name<>'аукцион в электронной форме' 
And date_trunc('day',con.signdate)<to_date('${date}','yyyy-mm-dd');

Insert Into nrpz.erc_${year}_list_contract
Select  
	Distinct sch.org_name,
	sch.org_inn,
	sch.org_spz,
	sch.org_kgntv,sch.grbsid,
	sch.plannumber,
	sch.versionnumber,
	sch.publishdate,
	sch.positionnumber,
	sch.ikz,
	sch.finance_total nmc_schedule,
	sch.purchasecanceled,
	sch.specialpurchase_type,
	sch.modiff_all cnt_modif_pg,
	Null reqnum,
	NULL::timestamp publishdate_reqnum,
	Null sop_code_reqnum,
	Null sop_name_reqnum,
	Null joflag_org_name,
	Null joflag_org_spz,
	NULL::int2 org_kgntv_joflag,
	NULL::int2 joflag,
	Null::timestamp startdate,
	Null::timestamp enddate,
	NULL::numeric nmc_reqnum,
	NULL::numeric nmc_joflag,
	Null::timestamp biddingdate,
	Null::timestamp openingdate,
	Null::timestamp scoringdate,
	Null prequalification,
	NULL::int4 lotnumber,
	Null positionnumber_reqnum,
	Case 
		When con.singlecustomer_name like 'Пункт 25 части 1 статьи 93%' OR con.singlecustomer_name IS null
		Then 1 Else 0 End flag_comp_reqnum, -- правка от 01.10.24
	Null ikz_reqnum,
	Null plannumber_reqnum,
	Null object_name_reqnum,
	NULL::int4 cnt_modif_reqnum,
	NULL::int2 flag_cans_reqnum,
	NULL::int2 purchasenumber_rn,
	sch.flah_act_version,
	0 flag_smp, -- флаг смп от 01.04.2025
	con.rnk,
	con.rnk_number,
	con.ikz ikz_con,
	con.signdate,
	con.publishdate_first publishdate_con,
	con.publishdate_last publishdate_con_last,
	con.versionnumber_first versionnumber_con,
	con.versionnumber_last versionnumber_con_last,
	con.notificationnumber reqnum_con,
	con.lotnumber lotnumber_con,
	con.sop_name sop_name_con,
	con.singlecustomer_name oneex_con,
	con.protocoldate protocoldate_con,
	con.price ck_first,
	con.price_cur ck_last,
	con.stage stage_con,
	con.executions_date,
	con.rejected_date,
	con.rejected_paid,
	con.rejected_reason,
	con.rejected_reason_name,
	con.penalties_type,
	con.penalties_party,
	con.penalties_amount,
	con.executionperiod_end plan_execution_date_con,
	--con.supplier_type,
	con.supplier_fullname,
	con.supplier_inn,
	con.supplier_kpp,
	con.object_name object_name_con,
	con.org_name org_name_con,
	con.org_inn org_inn_con,
	con.org_spz org_spz_con,
	con.org_kgntv_contract,
	con.protocoldate_publ,
	con.protocoldate_sign,
	con.protocoldate_one_publ,
	con.protocoldate_one_sign,
	con.firstnoticesuccesdate,
	con.flag_16,
	con.cnt_modif cnt_modif_con,
	con.type_,
	con.flag_evasion,
	con.pricetype,
    con.lotid, --правки от 30.06.23 добавить lot id
    con.is_structured_form,
    con.requestid,
	con.contract_project_number, 
	con.contract_price_changed_supplier_protocol, 
	con.justification_contract_price_change
From nrpz.erc_${year}_contract con
Inner Join nrpz.erc_dwh_organization_kgntv o On con.org_spz = o.spz And o.id not in (3039,2913,31344,2998,3020,2901,3024,2994,7817,3774,29714,3127,3128,3132,3133,2147,3011,1556,10288,87212,1610)
Inner Join nrpz.erc_dwh_organization_kgntv dokgrbs   On dokgrbs.id = o.parentid -- And dokgrbs.id <> 3039 хз нужен этот грбс или нет в рейтинге не учитывается 
Inner Join nrpz.erc_organization eo   On eo.spz = dokgrbs.spz 
Inner Join nrpz.erc_dwh_contract_kgntv_${srez_number} cont On cont.contractrnk=con.rnk
Inner Join nrpz.erc_dwh_procedures_kgntv_${srez_number} proc On proc.lotuuid::int4=cont.lotid
Inner Join nrpz.erc_${year}_schedule_pos sch On sch.ikz=proc.pg_ikz And con.notificationnumber Is Null And con.positionnumber Is Null
Left Join nrpz.erc_${year}_list_contract t On t.rnk=con.rnk
Where t.rnk Is Null And date_trunc('day', con.signdate) < to_date('${date}','yyyy-mm-dd'); --контракты из среза, если вдруг не попали ранее

/*
Insert Into nrpz.erc_${year}_list_contract
Select 
	Distinct sch.org_name,
	sch.org_inn,
	sch.org_spz,
	sch.org_kgntv,sch.grbsid,
	sch.plannumber,
	sch.versionnumber,
	sch.publishdate,
	sch.positionnumber,
	sch.ikz,
	sch.finance_total nmc_schedule,
	sch.purchasecanceled,
	sch.specialpurchase_type,
	sch.modiff_all cnt_modif_pg,
	Null reqnum,
	NULL::timestamp publishdate_reqnum,
	Null sop_code_reqnum,
	Null sop_name_reqnum,
	Null joflag_org_name,
	Null joflag_org_spz,
	NULL::int2 org_kgntv_joflag,
	NULL::int2 joflag,
	Null::timestamp startdate,
	Null::timestamp enddate,
	NULL::numeric nmc_reqnum,
	NULL::numeric nmc_joflag,
	Null::timestamp biddingdate,
	Null::timestamp openingdate,
	Null::timestamp scoringdate,
	Null prequalification,
	NULL::int4 lotnumber,
	Null positionnumber_reqnum,
	Case 
		When con.singlecustomer_name like 'Пункт 25 части 1 статьи 93%' OR con.singlecustomer_name IS null
		Then 1 Else 0 End flag_comp_reqnum, -- правка от 01.10.24
	Null ikz_reqnum,
	Null plannumber_reqnum,
	Null object_name_reqnum,
	NULL::int4 cnt_modif_reqnum,
	NULL::int2 flag_cans_reqnum,
	NULL::int2 purchasenumber_rn,
	sch.flah_act_version,
	0 flag_smp, -- флаг смп от 01.04.2025
	con.rnk,
	con.rnk_number,
	con.ikz ikz_con,
	con.signdate,
	con.publishdate_first publishdate_con,
	con.publishdate_last publishdate_con_last,
	con.versionnumber_first versionnumber_con,
	con.versionnumber_last versionnumber_con_last,
	con.notificationnumber reqnum_con,
	con.lotnumber lotnumber_con,
	con.sop_name sop_name_con,
	con.singlecustomer_name oneex_con,
	con.protocoldate protocoldate_con,
	con.price ck_first,
	con.price_cur ck_last,
	con.stage stage_con,
	con.executions_date,
	con.rejected_date,
	con.rejected_paid,
	con.rejected_reason,
	con.rejected_reason_name,
	con.penalties_type,
	con.penalties_party,
	con.penalties_amount,
	con.executionperiod_end plan_execution_date_con,
	--con.supplier_type,
	con.supplier_fullname,
	con.supplier_inn,
	con.supplier_kpp,
	con.object_name object_name_con,
	con.org_name org_name_con,
	con.org_inn org_inn_con,
	con.org_spz org_spz_con,
	con.org_kgntv_contract,
	con.protocoldate_publ,
	con.protocoldate_sign,
	con.protocoldate_one_publ,
	con.protocoldate_one_sign,
	con.firstnoticesuccesdate,
	con.flag_16,
	con.cnt_modif cnt_modif_con,
	con.type_,
	con.flag_evasion,
	con.pricetype,
    con.lotid, --правки от 30.06.23 добавить lot id
    con.is_structured_form,
    con.requestid,
	con.contract_project_number, 
	con.contract_price_changed_supplier_protocol, 
	con.justification_contract_price_change
From nrpz.erc_${year}_schedule_pos sch
Inner Join nrpz.erc_${year}_contract con On sch.positionnumber=con.positionnumber --позиции у которых есть контракты, которых нет в list + не берем аукц. в электрон форме
Where  con.rnk not in (Select 
							Distinct rnk 
					   From nrpz.erc_${year}_list_contract
					   Where rnk Is Not Null)
And con.sop_name<>'аукцион в электронной форме'
And date_trunc('day',con.signdate) < to_date('${date}','yyyy-mm-dd');
*/


UPDATE nrpz.erc_${year}_list_contract
SET 
rnk=null,
rnk_number=null,
ikz_con=null,
signdate=null,
publishdate_con=null,
publishdate_con_last=null,
versionnumber_con=null,
versionnumber_con_last=null,
reqnum_con=null,
lotnumber_con=null,
sop_name_con=null,
oneex_con=null,
protocoldate_con=null,
ck_first=null,
ck_last=null,
stage_con=null,
executions_date=null,
rejected_date=null,
rejected_paid=null,
rejected_reason=null,
rejected_reason_name=null,
penalties_type=null,
penalties_party=null,
penalties_amount=null,
plan_execution_date_con=null,
--supplier_type=null,
supplier_fullname=null,
supplier_inn=null,
supplier_kpp=null,
object_name_con=null,
org_name_con=null,
org_inn_con=null,
org_spz_con=null,
org_kgntv_contract=null,
protocoldate_publ=null,
protocoldate_sign=null,
protocoldate_one_publ=null,
protocoldate_one_sign=null,
firstnoticesuccesdate=null,
flag_16=null,
cnt_modif_con=null,
type_=null,
flag_evasion=null,
pricetype=null,
lotid=NULL,
is_structured_form=NULL,
requestid=NULL,
contract_project_number = NULL, 
justification_contract_price_change = NULL
Where date_trunc('day',publishdate_con)>to_date('${date2}','YYYY-MM-DD') and date_trunc('day', publishdate)< to_date('${date}','YYYY-MM-DD');
-- Для закупок, которые опубликованы в отчетном периоде, а информация по контрактам опубликована вне отчетного периода	делаем update по столбцам контракта

DELETE from nrpz.erc_${year}_list_contract
where 
grbsid=1894
or (reqnum is null and rnk is null); --записи у которых нет извещения и нет контракта
or date_trunc('day',publishdate_con)>to_date('${date2}','YYYY-MM-DD') and date_trunc('day',publishdate)>to_date('${date}','YYYY-MM-DD'));

--правка 3.1 3 кв 2025, котнтракты с конкурентным СОП
UPDATE nrpz.erc_${year}_list_contract
SET flag_comp_reqnum = 1 
WHERE rnk IN (
'2780113695125000029',
'2780214105525000004',
'2780214105525000005',
'2780214105525000006',
'2780213963425000010',
'2780264819825000015',
'2780509489325000193',
'2780509489325000194',
'2780509489325000195',
'2780509489325000187',
'2780509489325000191',
'2780509489325000192',
'2780509489325000205',
'2780547060425000024',
'2780547060425000025',
'2780547060425000022',
'2780547060425000026',
'2780547060425000027',
'2780547060425000030',
'2780514505825000018',
'2780702609525000020',
'2780702609525000013',
'2780702609525000014',
'2780702609525000015',
'2780702609525000018',
'2780702609525000019',
'2780702609525000023',
'2780702609525000024',
'2780702609525000025',
'2780725107625000028',
'2781326452425000027',
'2781445311525000022',
'2780727692325000068',
'2780303224225000056',
'2780303224225000059',
'2780303224225000067',
'2780410487725000303',
'2782543079025000008',
'2780575021725000035',
'2780575021725000036',
'2780457641425000005',
'2780900833425000064')
;
-- правка 8.1 3 кв 2025
UPDATE nrpz.erc_${year}_list_contract
SET sop_name_reqnum = 'Закупка, осуществляемая в соответствии с частью 12 статьи 93 Закона № 44-ФЗ'
WHERE rnk IN ('2780213982825000026',
'2780264819825000016',
'2780213982825000029',
'2780213982825000034',
'2780213982825000022',
'2780264819825000018',
'2780213982825000019',
'2780213982825000017',
'2780213982825000023',
'2780213982825000021',
'2780213982825000033',
'2780213982825000027',
'2780213982825000030',
'2780213982825000032',
'2780213982825000025',
'2780213982825000039',
'2780213982825000031',
'2780213982825000018',
'2780213982825000028',
'2780213982825000020',
'2780213982825000024',
'2782512811725000018');

